blank_issues_enabled: false
contact_links:
  - name: Soru / Destek
    url: https://github.com/ozhangebesoglu/to-do-electron/discussions
    about: Genel sorular veya yardım için Discussions kullanın.
